kind: pipeline
type: docker
name: default
steps:
  - name: greeting
    image: alpine
    commands:
      - echo hello
      - echo world
  - name: notify
    image: fifsky/drone-wechat-work
    pull: always
    settings:
      url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=43d424c0-3581-4e26-a9a3-c985ac48e31b
      msgtype: markdown
      content: |
        {{if eq .Status "success" }}
        #### 🎉 ${DRONE_REPO} 构建成功
        > Commit: [${DRONE_COMMIT_MESSAGE}](${DRONE_COMMIT_LINK})
        > Author: ${DRONE_COMMIT_AUTHOR}
        > [点击查看](${DRONE_BUILD_LINK})
        {{else}}
        #### ❌ ${DRONE_REPO} 构建失败
        > Commit: [${DRONE_COMMIT_MESSAGE}](${DRONE_COMMIT_LINK})
        > Author: ${DRONE_COMMIT_AUTHOR}
        > 请立即修复!!!
        > [点击查看](${DRONE_BUILD_LINK})
        {{end}}
    when:
      status:
        - failure
        - success
